import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// виправити та зберегти
export const metadata: Metadata = {
  title: 'Create Next App', //--remember
  description: 'Generated by create next app', //--remember
  openGraph: {
    title: 'Expense Tracker', //--remember
    description: 'Track your daily expenses and income in one place.', //--remember
    url: `${process.env.NEXT_PUBLIC_API_URL}`, //--remember
    images: [
      {
        url: `${process.env.NEXT_PUBLIC_API_URL}/images/bg-image-tablet.png`, //--remember
        width: 1200,
        height: 630,
        alt: 'Expense Tracker', //--remember
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" type="image/svg+xml" href="/vite.svg" />
      </head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
