import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import { Toaster } from 'react-hot-toast';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// виправити та зберегти
export const metadata: Metadata = {
  title: 'Travel Trucks',
  description: 'Generated by create next app', //--remember
  openGraph: {
    title: 'Travel Trucks',
    description: 'Track your daily expenses and income in one place.', //--remember
    url: `${process.env.NEXT_PUBLIC_my_URL}`, //--remember
    images: [
      {
        url: `${process.env.NEXT_PUBLIC_my_URL}/images/hero-image.jpg`,
        width: 1200,
        height: 630,
        alt: 'Travel Trucks',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" type="image/svg+xml" href="/vite.svg" />
      </head> */}
      <body className={inter.className}>
        <TanStackProvider>{children}</TanStackProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
