import Article from '@/components/Article/Article';
import css from './CatalogPage.module.css';
import Button from '@/components/Button/Button';

function CatalogPage() {
  const campers = [
    {
      id: 'cmniy1dvz000eyyoxgtlipyo4',
      name: 'Britz 4 Berth',
      price: 9000,
      rating: 4.4,
      location: 'Ukraine, Dnipro',
      description:
        "Experience luxury on the road with the Britz 4 Berth motorhome. Perfect for couples or small families, this alcove-style RV combines style, comfort, and functionality to provide an unforgettable travel experience. Whether you're exploring scenic landscapes or camping under the stars, the Britz 4 Berth offers a home-like atmosphere wherever your adventures take you.",
      form: 'alcove',
      length: '6.4m',
      width: '2.65m',
      height: '3.65m',
      tank: '208l',
      consumption: '30l/100km',
      transmission: 'manual',
      engine: 'petrol',
      amenities: [
        'ac',
        'bathroom',
        'kitchen',
        'tv',
        'radio',
        'refrigerator',
        'microwave',
        'water',
      ],
      createdAt: '2026-04-03T13:32:46.607Z',
      updatedAt: '2026-04-03T13:32:46.607Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/britz-4-berth/britz-4-berth-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dvu0007yyox23jbyl9k',
      name: 'Cruise America C-21',
      price: 8000,
      rating: 4.3,
      location: 'Ukraine, Poltava',
      description:
        'Discover the charm of the open road with the Cruise America C-21, a compact and versatile alcove-style motorhome. Ideal for couples or small families, this motorhome combines practicality with comfort, offering an efficient and enjoyable travel experience. The Cruise America C-21 is designed to provide you with the freedom to explore while ensuring a cozy retreat at the end of the day.',
      form: 'alcove',
      length: '6.4m',
      width: '2.34m',
      height: '3.72m',
      tank: '151l',
      consumption: '21l/100km',
      transmission: 'automatic',
      engine: 'petrol',
      amenities: [
        'ac',
        'bathroom',
        'kitchen',
        'radio',
        'refrigerator',
        'microwave',
        'gas',
        'water',
      ],
      createdAt: '2026-04-03T13:32:46.602Z',
      updatedAt: '2026-04-03T13:32:46.602Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/cruise-america-c-21/cruise-america-c-21-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dwi0016yyoxraajipay',
      name: 'El Monte Class A Family Sleeper [AF]',
      price: 15000,
      rating: 4.4,
      location: 'Ukraine, Sumy',
      description:
        'Indulge in the ultimate road trip experience with the El Monte Class A Family Sleeper [AF]. This fully integrated motorhome is a haven on wheels, offering unmatched luxury and comfort for families or groups of six. From its stylish design to the array of premium amenities, the El Monte Class A Family Sleeper [AF] redefines the standards of elegance on the open road.',
      form: 'integrated',
      length: '9.44m',
      width: '2.2m',
      height: '4m',
      tank: '302l',
      consumption: '33l/100km',
      transmission: 'automatic',
      engine: 'diesel',
      amenities: [
        'ac',
        'bathroom',
        'kitchen',
        'tv',
        'radio',
        'refrigerator',
        'microwave',
        'gas',
        'water',
      ],
      createdAt: '2026-04-03T13:32:46.626Z',
      updatedAt: '2026-04-03T13:32:46.626Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/el-monte-class-a-family-sleeper-af/el-monte-class-a-family-sleeper-af-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dx9002cyyoxn6gjltkl',
      name: 'El Monte Class B Small [B]',
      price: 10000,
      rating: 4.4,
      location: 'Ukraine, Odesa',
      description:
        'Discover the perfect blend of comfort and convenience with the El Monte Class B Small [B]. Ideal for couples with children, this compact panel truck offers a cozy interior with all the essential amenities for a delightful journey. Enjoy the freedom of the open road while relishing the convenience of on-the-go living in this stylish and well-equipped camper.',
      form: 'panel_van',
      length: '6m',
      width: '2.06m',
      height: '2.87m',
      tank: '117l',
      consumption: '14l/100km',
      transmission: 'manual',
      engine: 'diesel',
      amenities: ['ac', 'bathroom', 'kitchen', 'radio', 'refrigerator', 'gas'],
      createdAt: '2026-04-03T13:32:46.653Z',
      updatedAt: '2026-04-03T13:32:46.653Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/el-monte-class-b-small-b/el-monte-class-b-small-b-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dw8000syyoxmwrf4lvv',
      name: 'El Monte Class C Small [C]',
      price: 11000,
      rating: 4.4,
      location: 'Ukraine, Odesa',
      description:
        "Experience the perfect blend of compact design and functionality with the El Monte Class C Small [C]. Tailored for small families or groups of four, this motorhome provides a cozy and efficient way to explore the open roads and create lasting memories. Whether you're planning a weekend getaway or an extended road trip, the El Monte Class C Small [C] offers a hassle-free and comfortable travel experience.",
      form: 'alcove',
      length: '6.4m',
      width: '2.54m',
      height: '3.4m',
      tank: '208l',
      consumption: '25l/100km',
      transmission: 'manual',
      engine: 'diesel',
      amenities: [
        'ac',
        'bathroom',
        'kitchen',
        'tv',
        'radio',
        'refrigerator',
        'microwave',
        'gas',
        'water',
      ],
      createdAt: '2026-04-03T13:32:46.617Z',
      updatedAt: '2026-04-03T13:32:46.617Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/el-monte-class-c-small-c/el-monte-class-c-small-c-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dy7003wyyoxdkfmn17v',
      name: 'Freedom Cruiser',
      price: 10000,
      rating: 4.4,
      location: 'Ukraine, Lviv',
      description: 'Enjoy the freedom of the road with the Freedom Cruiser...',
      form: 'panel_van',
      length: '6.5m',
      width: '2.1m',
      height: '2.9m',
      tank: '140l',
      consumption: '15l/100km',
      transmission: 'automatic',
      engine: 'petrol',
      amenities: ['ac', 'kitchen', 'tv', 'radio', 'refrigerator', 'water'],
      createdAt: '2026-04-03T13:32:46.687Z',
      updatedAt: '2026-04-03T13:32:46.687Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/freedom-cruiser/freedom-cruiser-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dx50025yyoxdpij4zx8',
      name: 'HI-Top Camper',
      price: 9000,
      rating: 4.4,
      location: 'Ukraine, Odesa',
      description:
        'Elevate your road trip experience with the HI-Top Camper, a perfect blend of comfort and functionality. Designed for small groups or couples, this compact panel truck offers a spacious interior with essential amenities for a memorable journey. Enjoy the freedom of the open road while experiencing the convenience of on-the-go living.',
      form: 'panel_van',
      length: '5.6m',
      width: '2m',
      height: '3.1m',
      tank: '117l',
      consumption: '14l/100km',
      transmission: 'automatic',
      engine: 'petrol',
      amenities: ['ac', 'kitchen', 'radio', 'microwave', 'water'],
      createdAt: '2026-04-03T13:32:46.649Z',
      updatedAt: '2026-04-03T13:32:46.649Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/hi-top-camper/hi-top-camper-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dxm002xyyoxixchd58x',
      name: 'Horizon Adventurer',
      price: 11000,
      rating: 4.6,
      location: 'Ukraine, Kyiv',
      description:
        'Set out for the horizon in the Horizon Adventurer, a fully equipped panel truck with all the comforts of home...',
      form: 'panel_van',
      length: '6.3m',
      width: '2.2m',
      height: '3.0m',
      tank: '120l',
      consumption: '14.2l/100km',
      transmission: 'automatic',
      engine: 'petrol',
      amenities: [
        'ac',
        'kitchen',
        'tv',
        'radio',
        'refrigerator',
        'microwave',
        'gas',
        'water',
      ],
      createdAt: '2026-04-03T13:32:46.666Z',
      updatedAt: '2026-04-03T13:32:46.666Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/horizon-adventurer/horizon-adventurer-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dxu003byyoxaqcfh540',
      name: 'Journey Escape',
      price: 9000,
      rating: 4.5,
      location: 'Ukraine, Odesa',
      description:
        "Take a journey you'll never forget with the Journey Escape, a comfortable and efficient panel truck...",
      form: 'panel_van',
      length: '5.9m',
      width: '2.1m',
      height: '2.6m',
      tank: '118l',
      consumption: '13.5l/100km',
      transmission: 'automatic',
      engine: 'petrol',
      amenities: ['ac', 'kitchen', 'tv', 'radio', 'microwave', 'water'],
      createdAt: '2026-04-03T13:32:46.675Z',
      updatedAt: '2026-04-03T13:32:46.675Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/journey-escape/journey-escape-1.jpg',
      totalReviews: 2,
    },
    {
      id: 'cmniy1dx0001yyyoxyac2tiki',
      name: 'Kuga Camper',
      price: 8500,
      rating: 4.4,
      location: 'Ukraine, Kyiv',
      description:
        'Embark on a comfortable and convenient road trip with the Kuga Camper panel truck. Designed for small groups or couples, this compact camper offers a blend of functionality and style. Explore the open roads with ease, enjoy the convenience of on-the-go cooking, and experience the freedom of a camper designed for memorable adventures.',
      form: 'panel_van',
      length: '5.6m',
      width: '2m',
      height: '3.1m',
      tank: '117l',
      consumption: '15l/100km',
      transmission: 'automatic',
      engine: 'diesel',
      amenities: ['ac', 'kitchen', 'radio', 'microwave', 'gas'],
      createdAt: '2026-04-03T13:32:46.645Z',
      updatedAt: '2026-04-03T13:32:46.645Z',
      coverImage:
        'https://ac.goit.global/fullstack/career/campers/kuga-camper/kuga-camper-1.jpg',
      totalReviews: 2,
    },
  ];
  console.log('Доступные стили:', css);
  return (
    <>
      <div className={css['list-articlies']}>
        {campers.map(camper => {
          return <Article key={camper.id} camper={camper} />;
        })}
      </div>
      <Button text="Load more" className={css['button-outh-color']} />
    </>
  );
}

export default CatalogPage;
